using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace ProyectoFinal
{
    public partial class frmAsignProducts : DevExpress.XtraEditors.XtraForm
    {
        DataAccess da = new DataAccess();
        string IDSucursal = "";
        public frmAsignProducts()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void frmAsignProducts_Load(object sender, EventArgs e)
        {
            LoadData();
        }

        public void LoadData()
        {
            //Cargamos las Sucursales, Productos y presentaciones.
            //SUCURSALES            
            gridLookUpSucursales.Properties.DataSource = da.fillDataTable("SELECT id_sucursal, nombre_sucursal from tblSucursal");
            gridLookUpSucursales.Properties.DisplayMember = "nombre_sucursal";
            gridLookUpSucursales.Properties.ValueMember = "id_sucursal";

            //
            //PRODUCTOS
            //
            gridLookUpProduct.Properties.DataSource = da.fillDataTable("SELECT id_producto, nombre_producto from tblProducto");
            gridLookUpProduct.Properties.DisplayMember = "nombre_producto";
            gridLookUpProduct.Properties.ValueMember = "id_producto";            

        }

        private void gridLookUpProduct_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                string query = "select tblAsignacionPrecio.id_Presentacion AS 'ID', tblPresentacion.tipo_presentacion AS 'Presentacion' from tblAsignacionPrecio ";
                query += "INNER JOIN tblPresentacion ON tblPresentacion.id_Presentacion = tblAsignacionPrecio.id_presentacion ";
                query += "WHERE id_producto='{0}';";
                query = string.Format(query, gridLookUpProduct.EditValue.ToString());

                gridLookUpPresentacion.Properties.DataSource = da.fillDataTable(query);
                gridLookUpPresentacion.Properties.DisplayMember = "Presentacion";
                gridLookUpPresentacion.Properties.ValueMember = "ID";
            }

            catch (Exception ex)
            {
                MessageBox.Show("Debe seleccionar al menos un producto y Sucursal \n Detalles del error:"+ex.Message);
            }

        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnAceptar_Click(object sender, EventArgs e)
        {
            //AGREGANDO EL DATO A LA BASE, 
            //SE AGREGA AL KARDEX LA CREACION DEL PRODUCTO EN LA SUCURSAL
            //Y ASI COMPLETAR LOS CAMPOS QUE REQUIEREN

            string query = "SELECT tblAsignacionPrecio.id_asignacionprecio from tblAsignacionPrecio WHERE id_producto = '{0}' AND id_presentacion = {1};";
            //Parametrizando.
            query = string.Format(query, gridLookUpProduct.EditValue.ToString(), gridLookUpPresentacion.EditValue.ToString());
            int idPrecio= da.executeCommand(query);
            int idSucursal = Convert.ToInt16(gridLookUpSucursales.EditValue);

            try
            {
                //insertamos el dato.
                //PRIMERO EN TABLASIGNACION PRODUCTO

                string command = "INSERT INTO tblAsignacionProducto(id_sucursal, id_producto) VALUES ({0},'{1}')";
                command = string.Format(command, gridLookUpSucursales.EditValue.ToString(), gridLookUpProduct.EditValue.ToString());
                da.executeCommand(command);
                //insertamos el dato.
                //AHORA EN EL KARDEX.
                command = "INSERT INTO tblKardex(fecha,documento,cantidad_inicial,cantidad_final,id_asignacionprecio,id_sucursal) ";
                command += "VALUES('{0}','{1}',0,0,(SELECT tblAsignacionPrecio.id_asignacionprecio from tblAsignacionPrecio WHERE id_producto = '{2}' AND id_presentacion = {3}),{4})";
                command = string.Format(command,
                    DateTime.Today.ToString("yyyy-MM-dd"),
                    "INICIO PROD ",
                    gridLookUpProduct.EditValue.ToString(),
                    gridLookUpPresentacion.EditValue.ToString(),
                    gridLookUpSucursales.EditValue.ToString());
                da.executeCommand(command);

                MessageBox.Show("Producto Agregado correctamente. ", "Informacion", MessageBoxButtons.OK,MessageBoxIcon.Information);
                LoadData();


            }
            catch (Exception ex)
            {
                MessageBox.Show("Error al asignar el producto. \n Detalles del error: "+ex.Message);
                
            }

            


        }
    }
}